### ISSUE TITLE
可以用吗?

### ISSUE THREAD

**Issue by firstpersonl** [XiaohuaCN/Cloud-Radar-Plus#12]
还在首页写那么多，:clap:

**Comment by huangwc94** [comment]
目前我认为原作者有可能是https://github.com/txchen/scichicken
因为在这个package里面用了一个非常小众的依赖，叫light-server，这个玩意也是txchen写的。自己写的雷达用自己写的依赖应该是很自然的一件事。而且还没看到比这个repo更早创建的js版雷达。
虽然你可以说这个repo主copy了别人，但是注意，txchen2个月以前就断更了，这个repo主反而在持续更新。教程也是最详细的，现在3.8版本的吃鸡又改了加密方式，希望本repo主有能力破解把。
另外，有句话希望各位用户注意：闷声发大财。
和js版本雷达一起开源的Kolitn版本前几天已经断更了，断更原因就是这种网络嗅探雷达在国内太火了。
希望各位且用且珍惜。
