### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by morigamio** [XiaohuaCN/Cloud-Radar-Plus#2]
Hello!

I have the next problems detected.

- Cant see the players name, only guid.
- The health of players its crazy.
- Items never disapear after pick up.
- The map cant follow me when I use vehicule.

**Comment by BobZbf** [comment]
你好 
我可以打开雷达页面,
sstap测试tcp与udp都通过了,
可是进入游戏后却无法显示物资及敌人也就是没有任何效果,
我是连接sstap后再用uu加速器的(直接用sstap无法登录游戏),和这有关系嘛
请问该如何解决

**Comment by XiaohuaCN** [comment]
用sstap 后不要使用其他加速器。不然你游戏流量就不走你搭建好的ss服务器了而是走你开的加速器。  你的雷达服务器也就无法获取到你的游戏了。

**Comment by rewq911** [comment]
UDP不会掉线吗。。。。
