### ISSUE TITLE
感谢地图上传

### ISSUE THREAD

**Issue by zsg0601** [XiaohuaCN/Cloud-Radar-Plus#5]
我本来也想本地化地图，但是考虑到本地化后每次部署需要重新加载70M的文件，就放弃了，而且github上传文件还麻烦，地图文件系统又复杂！
目前来看PUBG针对每一局游戏都会有一个新的密钥进行编码，且抓包后外部解码每6小时需要更新一次，估计这个雷达很快就要被废弃了，还希望你能找到更多程序猿一起维护这个项目！

**Comment by Zayia** [comment]
先见之明
