### ISSUE TITLE
网页问题

### ISSUE THREAD

**Issue by shinegod** [XiaohuaCN/Cloud-Radar-Plus#6]
为什么按照脚本搭建好了以后，26008 没有启动起来？

**Comment by XiaohuaCN** [comment]
重新搭建 用脚本搭建 检查20086 端口是否映射  SStap的测试TCP 和UDP 是否都绿色通过

**Comment by shinegod** [comment]
就是用脚本搭建的，SStap的测试TCP 和UDP 都绿色通过
