### ISSUE TITLE
请问是装雷达送妹子吗？

### ISSUE THREAD

**Issue by coolchenK** [XiaohuaCN/Cloud-Radar-Plus#9]
RT>打开页面吓我一跳
![image](https://user-images.githubusercontent.com/13838753/39639150-083162de-4ffb-11e8-81d6-4f351462955f.png)

**Comment by xXSkrill1337** [comment]
你好這雷達工作？

**Comment by Tom9998** [comment]
它还不工作

**Comment by xXSkrill1337** [comment]
哦好的謝謝
